#!/usr/bin/env python3
"""Test script to verify generated_by field in RAG responses."""
import json
from rag_engine import vectorize_and_store, ask

# Load sample report
with open('sample_forensic_report.json', 'r') as f:
    report_json = json.load(f)

# Vectorize
collection_name = vectorize_and_store("test_analysis_02", report_json)

# Test 1: Forensic query with LLM
print("=" * 70)
print("TEST 1: Forensic Query (with Llama 3)")
print("=" * 70)
result = ask(collection_name, "What suspicious files were found?", top_k=5, use_llm=True)
print(f"Question: What suspicious files were found?")
print(f"Generated By: {result['generated_by']}")
print(f"Answer: {result['answer'][:150]}...")
print()

# Test 2: Small talk
print("=" * 70)
print("TEST 2: Small Talk (Chat)")
print("=" * 70)
result = ask(collection_name, "hey there", top_k=5, use_llm=True)
print(f"Question: hey there")
print(f"Generated By: {result['generated_by']}")
print(f"Answer: {result['answer'][:150]}...")
print()

# Test 3: Query with fallback (no context)
print("=" * 70)
print("TEST 3: Off-topic Query (Fallback)")
print("=" * 70)
result = ask(collection_name, "what is the capital of france", top_k=5, use_llm=True)
print(f"Question: what is the capital of france")
print(f"Generated By: {result['generated_by']}")
print(f"Answer: {result['answer'][:150]}...")
print()

# Test 4: Forensic query without LLM (fallback only)
print("=" * 70)
print("TEST 4: Forensic Query (Fallback, no LLM)")
print("=" * 70)
result = ask(collection_name, "How many deleted files were found?", top_k=5, use_llm=False)
print(f"Question: How many deleted files were found?")
print(f"Generated By: {result['generated_by']}")
print(f"Answer: {result['answer'][:150]}...")
